return {
    ensure_installed = {
        "isort",
        "black",
        "pylint",
        "tflint",
        "terraform_fmt",
        "gofumpt",
        "goimports_reviser",
        "golines",
        "golangci_lint",
        "yamllint",
        "yamlfmt",
        "buf",
        "google_java_format",
        "scalafmt",
        "shfmt",
        "sqlfluff",
        "terragrunt_fmt",
    },
    auto_install = true,
}
