return {
    auto_install = true,
    ensure_installed = {
        "python",
        "go",
        "bash",
        "terraform",
        "scala",
        "java",
        "jq",
        "yaml",
        "csv",
        "dockerfile",
        "dot",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "gomod",
        "gosum",
        "gotmpl",
        "gowork",
        "helm",
        "html",
        "http",
        "json",
        "kotlin",
        "lua",
        "sql",
        "xml",
    },
}
